spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/tenantDB}
server.port=${PORT:3001}
app.jwt-secret=${JWT_SECRET:change_this_jwt_secret_for_local_dev_123456}
app.jwt-expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.frontend-url=${FRONTEND_URL:https://tenant-notes-application-frontend.vercel.app}
app.client-dist-path=${CLIENT_DIST_PATH:../client/dist}
spring.jackson.serialization.write-dates-as-timestamps=false
